# title: "<span style='color: black; font-family: Bell MT;'>STEM</span><span style='color: rgb(255, 51, 153); font-family: Bell MT;'><i>inclusive</i></span>"
title2: STEMinclusive IIT Kanpur
email:              steminclusiveiitk@gmail.com
description:        
author:             STEMInclusive IITK
baseurl:            ""
url:                "https://steminclusiveiitk.org"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
